1641174463758	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1641177379649	Sync.SyncScheduler	DEBUG	Woke from sleep.
1641177379649	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1641177379649	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1641177379650	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1641177379754	Sync.Service	DEBUG	User-Agent: Firefox/95.0.1 (Linux x86_64) FxSync/1.97.0.20211215221728.desktop
1641177379754	Sync.Service	INFO	Starting sync at 2022-01-02 20:36:19 in browser session JV0P5f_oHVL3
1641177379754	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1641177379755	Sync.Status	INFO	Resetting Status.
1641177379755	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1641177379756	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1641177379756	FirefoxAccounts	DEBUG	getOAuthToken enter
1641177379756	FirefoxAccounts	TRACE	getCachedToken returning cached token
1641177379756	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1641177379756	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1641177379757	Sync.SyncAuthManager	INFO	Getting sync key
1641177379757	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1641177379757	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1641177379757	FirefoxAccounts	DEBUG	getOAuthToken enter
1641177379757	FirefoxAccounts	TRACE	getCachedToken returning cached token
1641177379757	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1641177379757	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1641177379757	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1641177380688	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1641177380688	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1641177380689	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1641177380690	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1641177381258	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1641177381259	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1641177381259	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1641177381259	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1641177381259	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1641177381259	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1641177381259	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1641177381260	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1641177381261	Sync.BulkKeyBundle	INFO	BulkKeyBundle being created for undefined
1641177381261	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/192493400/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1641177381262	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1641177381262	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1641177381262	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1641177381262	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1641177381262	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1641177381264	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
